### ISSUE TITLE
Ошибка при запуске версии 15.4.62

### ISSUE THREAD

**Issue by simgislab** [nextgis/NextGIS_QGIS_open#41]
>Не удалось загрузить модуль «processing» из [«c:/tools/NEXTGI~1/apps/qgis/./python', 'C:\Users\mdubinin\NextGIS QGIS/python', 'C:\Users\mdubinin\NextGIS QGIS/python/plugins', 'c:/tools/NEXTGI~1/apps/qgis/./python/plugins', 'c:\tools\NEXTGI~1\bin\python27.zip', 'c:\tools\NEXTGI~1\apps\Python27\DLLs', 'c:\tools\NEXTGI~1\apps\Python27\lib', 'c:\tools\NEXTGI~1\apps\Python27\lib\plat-win', 'c:\tools\NEXTGI~1\apps\Python27\lib\lib-tk', 'c:\tools\NEXTGI~1\bin', 'c:\tools\NEXTGI~1\apps\Python27', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\PIL', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\win32', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\win32\lib', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\Pythonwin', 'c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\Users\mdubinin\NextGIS QGIS/python»]

>Traceback (most recent call last):
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 196, in loadPlugin
    __import__(packageName)
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\__init__.py", line 29, in 
    from processing.tools.general import *
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\tools\general.py", line 28, in 
    from processing.core.Processing import Processing
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\core\Processing.py", line 47, in 
    from processing.algs.qgis.QGISAlgorithmProvider import QGISAlgorithmProvider
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\algs\qgis\QGISAlgorithmProvider.py", line 100, in 
    from RasterLayerStatistics import RasterLayerStatistics
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\algs\qgis\RasterLayerStatistics.py", line 35, in 
    from processing.tools import raster
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\mdubinin\NextGIS QGIS/python/plugins\processing\tools\raster.py", line 29, in 
    import numpy
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\__init__.py", line 137, in 
    import add_newdocs
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\add_newdocs.py", line 9, in 
    from numpy.lib import add_newdoc
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\lib\__init__.py", line 4, in 
    from type_check import *
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\lib\type_check.py", line 8, in 
    import numpy.core.numeric as _nx
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\core\__init__.py", line 8, in 
    import numerictypes as nt
  File "c:/tools/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:\tools\NEXTGI~1\apps\Python27\lib\site-packages\numpy\core\numerictypes.py", line 92, in 
    from numpy.core.multiarray import typeinfo, ndarray, array, \
ImportError: cannot import name datetime_data

>Версия Python:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

>Версия:
2.8.1-Wien Wien, 2bb884f

>Путь поиска Python: ['c:/tools/NEXTGI~1/apps/qgis/./python', u'C:\\Users\\mdubinin\\NextGIS QGIS/python', u'C:\\Users\\mdubinin\\NextGIS QGIS/python/plugins', 'c:/tools/NEXTGI~1/apps/qgis/./python/plugins', 'c:\\tools\\NEXTGI~1\\bin\\python27.zip', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\DLLs', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\plat-win', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\lib-tk', 'c:\\tools\\NEXTGI~1\\bin', 'c:\\tools\\NEXTGI~1\\apps\\Python27', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\win32', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'c:\\tools\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:\\Users\\mdubinin\\NextGIS QGIS/python']

**Comment by alisovenko** [comment]
Не воспроизводилась больше?

**Comment by simgislab** [comment]
не а, закрываю
